export const POST_TYPES = {
  FETCH_POST_LIST: "FETCH_POST_LIST",
  FETCH_POST_LIST_PENDING: "FETCH_POST_LIST_PENDING",
  FETCH_POST_LIST_FULFILLED: "FETCH_POST_LIST_FULFILLED",
  FETCH_POST_LIST_REJECTED: "FETCH_POST_LIST_REJECTED",
};

export const HEADER_TYPES = {
  SET_TITLE: "SET_TITLE",
  SET_COLOR: "SET_COLOR",
};
