export const FETCH_COMMENT_LIST = "FETCH_COMMENT_LIST";
export const FETCH_COMMENT_LIST_PENDING = "FETCH_COMMENT_LIST_PENDING";
export const FETCH_COMMENT_LIST_FULFILLED = "FETCH_COMMENT_LIST_FULFILLED";
export const FETCH_COMMENT_LIST_REJECTED = "FETCH_COMMENT_LIST_REJECTED";
